# Generated by Django 2.1.5 on 2019-02-10 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0010_album_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='user',
        ),
    ]
